# Dada Ki Jay Ho


version: '3'
services:
  membly-backend-app: 
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
