# Dada Ki Jay Ho


version: '3'
services:
  membly-backend-app: 
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass root"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db-data:/data/db
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - 6060:3000
    volumes:
      - grafana_data:/var/lib/grafana


volumes:
  mongo-db-data:
  grafana_data: {}
