# Dada Ki Jay Ho


version: '3'
services:
  membly-backend-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    environment:
      - PORT=4000
      - NODE_ENV=development
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start-dev
    env_file:
      - .env